// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASk6uF70pTP9B3pXQlY1iO2r6Sck4snqY',
    appId: '1:105082242698:web:f455595e2d9728c2454f73',
    messagingSenderId: '105082242698',
    projectId: 'smartwardrobe-33757',
    authDomain: 'smartwardrobe-33757.firebaseapp.com',
    storageBucket: 'smartwardrobe-33757.firebasestorage.app',
    measurementId: 'G-ZLS1E578D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIWrkWA9kvq0ALTjk-4uxntfYzdiF0S00',
    appId: '1:105082242698:android:8bd836432d52226f454f73',
    messagingSenderId: '105082242698',
    projectId: 'smartwardrobe-33757',
    storageBucket: 'smartwardrobe-33757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvI8bNqo5QelmOzM08deY7zMsTmte5_gM',
    appId: '1:105082242698:ios:141620e6e21d44c0454f73',
    messagingSenderId: '105082242698',
    projectId: 'smartwardrobe-33757',
    storageBucket: 'smartwardrobe-33757.firebasestorage.app',
    iosBundleId: 'com.example.smartwardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvI8bNqo5QelmOzM08deY7zMsTmte5_gM',
    appId: '1:105082242698:ios:141620e6e21d44c0454f73',
    messagingSenderId: '105082242698',
    projectId: 'smartwardrobe-33757',
    storageBucket: 'smartwardrobe-33757.firebasestorage.app',
    iosBundleId: 'com.example.smartwardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASk6uF70pTP9B3pXQlY1iO2r6Sck4snqY',
    appId: '1:105082242698:web:1b436cb13f896ea4454f73',
    messagingSenderId: '105082242698',
    projectId: 'smartwardrobe-33757',
    authDomain: 'smartwardrobe-33757.firebaseapp.com',
    storageBucket: 'smartwardrobe-33757.firebasestorage.app',
    measurementId: 'G-6XSWXX9YT6',
  );
}
