import '../models/clothing_item.dart';
import '../models/notification_model.dart';
import '../models/outfit.dart';
import '../models/user_model.dart';
import '../models/wardrobe_category.dart';
import 'constants.dart';

class DummyData {
  static final UserModel currentUser = UserModel(
    id: '',
    name: '',
    email: '',
    password: '',
    favoriteStyle: '',
    favoriteColor: '',
    profileImage: ImageConstants.profilePlaceholder,
  );

  static const List<WardrobeCategory> categories = [
    WardrobeCategory(name: 'All', subcategories: []),
    WardrobeCategory(
      name: 'Tops',
      subcategories: [
        'T-Shirts',
        'Shirts',
        'Blouses',
        'Crop Tops',
        'Hoodies',
        'Sweaters',
        'Tank Tops',
        'Polo Shirts',
        'Tunics',
        'Cardigans',
      ],
    ),
    WardrobeCategory(
      name: 'Bottoms',
      subcategories: [
        'Jeans',
        'Trousers',
        'Leggings',
        'Shorts',
        'Skirts',
        'Cargo Pants',
        'Joggers',
        'Wide-Leg Pants',
        'Formal Pants',
        'Denim Shorts',
      ],
    ),
    WardrobeCategory(
      name: 'Dresses',
      subcategories: [
        'Casual Wear',
        'Formal Wear',
        'Office Wear',
        'Wedding Dresses',
        'Party Wear',
        'Evening Gowns',
        'Traditional Wear',
        'Summer Dresses',
        'Maxi Dresses',
        'Mini Dresses',
      ],
    ),
    WardrobeCategory(
      name: 'Outerwear',
      subcategories: [
        'Jackets',
        'Coats',
        'Blazers',
        'Trench Coats',
        'Parkas',
        'Leather Jackets',
        'Denim Jackets',
        'Raincoats',
        'Puffer Jackets',
        'Capes',
      ],
    ),
    WardrobeCategory(
      name: 'Footwear',
      subcategories: [
        'Sneakers',
        'Running Shoes',
        'Flats',
        'Sandals',
        'Heels',
        'Boots',
        'Loafers',
        'Slippers',
        'Sports Shoes',
        'Formal Shoes',
      ],
    ),
    WardrobeCategory(
      name: 'Accessories',
      subcategories: [
        'Handbags',
        'Jewelry',
        'Watches',
        'Sunglasses',
        'Belts',
        'Scarves',
        'Hats & Caps',
        'Hair Accessories',
        'Wallets',
        'Perfumes',
      ],
    ),
  ];

  static const List<WardrobeCategory> maleCategories = [
    WardrobeCategory(name: 'All', subcategories: []),
    WardrobeCategory(
      name: 'Summer',
      subcategories: [
        'Shalwar Kameez',
        'Shirts',
        'Pants / Trousers',
        'Footwear',
      ],
    ),
    WardrobeCategory(
      name: 'Winter',
      subcategories: [
        'Shalwar Kameez',
        'Shirts',
        'Pants / Trousers',
        'Footwear',
      ],
    ),
    WardrobeCategory(
      name: 'Footwear',
      subcategories: [
        'Peshawari Chappal',
        'Sandals',
        'Formal Shoes',
        'Sneakers',
      ],
    ),
  ];

  static List<ClothingItem> clothingItems = [
    ClothingItem(
      id: '1',
      name: 'White Linen Shirt',
      category: 'Tops',
      subcategory: 'Shirts',
      color: 'White',
      season: 'Summer',
      imageUrl: ImageConstants.casual1,
      isFavorite: true,
      dressPieces: 1,
    ),
    ClothingItem(
      id: '2',
      name: 'Red Running Shoes',
      category: 'Footwear',
      subcategory: 'Running Shoes',
      color: 'Red',
      season: 'All Season',
      imageUrl: ImageConstants.shoes1,
      isFavorite: true,
    ),
    ClothingItem(
      id: '3',
      name: 'Blue Denim Jacket',
      category: 'Outerwear',
      subcategory: 'Denim Jackets',
      color: 'Blue',
      season: 'Fall',
      imageUrl: ImageConstants.jacket1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '4',
      name: 'Black Trousers',
      category: 'Bottoms',
      subcategory: 'Formal Pants',
      color: 'Black',
      season: 'All Season',
      imageUrl: ImageConstants.formal1,
      isFavorite: true,
      dressPieces: 1,
    ),
    ClothingItem(
      id: '5',
      name: 'Summer Floral Dress',
      category: 'Dresses',
      subcategory: 'Summer Dresses',
      color: 'Pink',
      season: 'Summer',
      imageUrl: ImageConstants.dress1,
      isFavorite: false,
      dressPieces: 1,
    ),
    ClothingItem(
      id: '6',
      name: 'Casual Street Hoodie',
      category: 'Tops',
      subcategory: 'Hoodies',
      color: 'Gray',
      season: 'Winter',
      imageUrl: ImageConstants.streetwear1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '7',
      name: 'Elegant Evening Gown',
      category: 'Dresses',
      subcategory: 'Evening Gowns',
      color: 'Black',
      season: 'All Season',
      imageUrl: ImageConstants.dress2,
      isFavorite: true,
      dressPieces: 3,
    ),
    ClothingItem(
      id: '8',
      name: 'Designer Handbag',
      category: 'Accessories',
      subcategory: 'Handbags',
      color: 'Brown',
      season: 'All Season',
      imageUrl: ImageConstants.accessory1,
      isFavorite: true,
    ),
    ClothingItem(
      id: '9',
      name: 'Brown Leather Loafers',
      category: 'Footwear',
      subcategory: 'Loafers',
      color: 'Brown',
      season: 'All Season',
      imageUrl: ImageConstants.shoes1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '10',
      name: 'Cashmere Pullover',
      category: 'Tops',
      subcategory: 'Sweaters',
      color: 'Gray',
      season: 'Winter',
      imageUrl: ImageConstants.casual2,
      isFavorite: false,
    ),
    ClothingItem(
      id: '11',
      name: 'Denim Shorts',
      category: 'Bottoms',
      subcategory: 'Denim Shorts',
      color: 'Blue',
      season: 'Summer',
      imageUrl: ImageConstants.streetwear1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '12',
      name: 'Gold Pendant Necklace',
      category: 'Accessories',
      subcategory: 'Jewelry',
      color: 'Gold',
      season: 'All Season',
      imageUrl: ImageConstants.accessory1,
      isFavorite: true,
    ),
    ClothingItem(
      id: '13',
      name: 'Silk Blouse',
      category: 'Tops',
      subcategory: 'Blouses',
      color: 'White',
      season: 'Spring',
      imageUrl: ImageConstants.casual1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '14',
      name: 'Casual Blazer',
      category: 'Outerwear',
      subcategory: 'Blazers',
      color: 'Blue',
      season: 'Spring',
      imageUrl: ImageConstants.jacket1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '15',
      name: 'Velvet Evening Heels',
      category: 'Footwear',
      subcategory: 'Heels',
      color: 'Black',
      season: 'All Season',
      imageUrl: ImageConstants.shoes1,
      isFavorite: true,
    ),
    ClothingItem(
      id: '16',
      name: 'Wool Overcoat',
      category: 'Outerwear',
      subcategory: 'Coats',
      color: 'Brown',
      season: 'Winter',
      imageUrl: ImageConstants.jacket1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '17',
      name: 'Leather Sandals',
      category: 'Footwear',
      subcategory: 'Sandals',
      color: 'Brown',
      season: 'Summer',
      imageUrl: ImageConstants.shoes1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '18',
      name: 'Statement Scarf',
      category: 'Accessories',
      subcategory: 'Scarves',
      color: 'Red',
      season: 'Winter',
      imageUrl: ImageConstants.accessory1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '19',
      name: 'White Sneakers',
      category: 'Footwear',
      subcategory: 'Sneakers',
      color: 'White',
      season: 'All Season',
      imageUrl: ImageConstants.shoes1,
      isFavorite: true,
    ),
    ClothingItem(
      id: '20',
      name: 'Leather Belt',
      category: 'Accessories',
      subcategory: 'Belts',
      color: 'Brown',
      season: 'All Season',
      imageUrl: ImageConstants.accessory1,
      isFavorite: false,
    ),
    ClothingItem(
      id: '21',
      name: 'Maxi Summer Dress',
      category: 'Dresses',
      subcategory: 'Maxi Dresses',
      color: 'White',
      season: 'Summer',
      imageUrl: ImageConstants.dress1,
      isFavorite: false,
      dressPieces: 2,
    ),
    ClothingItem(
      id: '22',
      name: 'Party Sequin Dress',
      category: 'Dresses',
      subcategory: 'Party Wear',
      color: 'Black',
      season: 'All Season',
      imageUrl: ImageConstants.dress2,
      isFavorite: true,
      dressPieces: 3,
    ),
  ];

  static List<Outfit> outfits = [
    Outfit(
      id: '1',
      title: 'Office Elegance',
      occasion: 'Office',
      imageUrl: ImageConstants.outfit1,
      items: ['White Linen Shirt', 'Black Formal Pants', 'Leather Loafers'],
      wardrobeType: 'female',
      isLiked: true,
    ),
    Outfit(
      id: '2',
      title: 'Casual Weekend',
      occasion: 'Casual',
      imageUrl: ImageConstants.outfit2,
      items: ['Graphic Tee', 'Denim Jacket', 'White Sneakers'],
      wardrobeType: 'female',
      isLiked: false,
    ),
    Outfit(
      id: '3',
      title: 'Party Glam',
      occasion: 'Party',
      imageUrl: ImageConstants.outfit3,
      items: ['Sequined Top', 'Leather Skirt', 'Heels'],
      wardrobeType: 'female',
      isLiked: true,
    ),
    Outfit(
      id: '4',
      title: 'Wedding Guest',
      occasion: 'Wedding',
      imageUrl: ImageConstants.outfit4,
      items: ['Floral Midi Dress', 'Clutch', 'Strappy Heels'],
      wardrobeType: 'female',
      isLiked: false,
    ),
    Outfit(
      id: '5',
      title: 'Street Style',
      occasion: 'Casual',
      imageUrl: ImageConstants.streetwear1,
      items: ['Oversized Hoodie', 'Cargo Pants', 'Chunky Sneakers'],
      wardrobeType: 'female',
      isLiked: false,
    ),
    Outfit(
      id: '6',
      title: 'Summer Breeze',
      occasion: 'Casual',
      imageUrl: ImageConstants.casual2,
      items: ['Cotton Dress', 'Straw Hat', 'Sandals'],
      wardrobeType: 'female',
      isLiked: true,
    ),
    Outfit(
      id: 'm1',
      title: 'Summer Traditional',
      occasion: 'Casual',
      imageUrl: ImageConstants.casual1,
      items: ['White Shalwar Kameez', 'Peshawari Chappal'],
      wardrobeType: 'male',
      isLiked: true,
    ),
    Outfit(
      id: 'm2',
      title: 'Formal Friday',
      occasion: 'Office',
      imageUrl: ImageConstants.formal1,
      items: ['Dress Shirt', 'Formal Pants', 'Loafers'],
      wardrobeType: 'male',
      isLiked: false,
    ),
    Outfit(
      id: 'm3',
      title: 'Winter Layers',
      occasion: 'Casual',
      imageUrl: ImageConstants.jacket1,
      items: ['Shalwar Kameez', 'Waistcoat', 'Leather Sandals'],
      wardrobeType: 'male',
      isLiked: true,
    ),
    Outfit(
      id: 'm4',
      title: 'Wedding Ready',
      occasion: 'Wedding',
      imageUrl: ImageConstants.outfit1,
      items: ['Embroidered Shalwar Kameez', 'Peshawari Chappal', 'Watch'],
      wardrobeType: 'male',
      isLiked: false,
    ),
    Outfit(
      id: 'm5',
      title: 'Street Casual',
      occasion: 'Casual',
      imageUrl: ImageConstants.streetwear1,
      items: ['T-Shirt', 'Jeans', 'Sneakers'],
      wardrobeType: 'male',
      isLiked: false,
    ),
    Outfit(
      id: 'm6',
      title: 'Party Night',
      occasion: 'Party',
      imageUrl: ImageConstants.outfit3,
      items: ['Black Shalwar Kameez', 'Dress Shoes', 'Watch'],
      wardrobeType: 'male',
      isLiked: true,
    ),
  ];

  static List<NotificationModel> notificationList = [
    NotificationModel(
      id: '1',
      title: 'Outfit Reminder',
      message:
          'You planned to wear "Office Elegance" tomorrow. Prepare your outfit!',
      type: 'reminder',
      icon: 'calendar_today',
      time: '2 min ago',
      isRead: false,
    ),
    NotificationModel(
      id: '2',
      title: 'Weather Update',
      message:
          'Tomorrow\'s forecast: 18°C with light rain. Consider adding a jacket.',
      type: 'weather',
      icon: 'wb_sunny',
      time: '1 hour ago',
      isRead: false,
    ),
    NotificationModel(
      id: '3',
      title: 'Wardrobe Tip',
      message:
          'Your "Red Running Shoes" haven\'t been worn in 30 days. Time to style them!',
      type: 'tip',
      icon: 'tips_and_updates',
      time: '3 hours ago',
      isRead: true,
    ),
    NotificationModel(
      id: '4',
      title: 'Style Inspiration',
      message:
          'New outfit suggestions available for "Party" occasion. Check them out!',
      type: 'inspiration',
      icon: 'lightbulb',
      time: '1 day ago',
      isRead: true,
    ),
    NotificationModel(
      id: '5',
      title: 'Seasonal Alert',
      message:
          'Summer is coming! Add your summer wardrobe items to be prepared.',
      type: 'seasonal',
      icon: 'ac_unit',
      time: '2 days ago',
      isRead: true,
    ),
    NotificationModel(
      id: '6',
      title: 'ClothingCare',
      message: 'Time for a wardrobe refresh. Consider donating unused items.',
      type: 'care',
      icon: 'volunteer_activism',
      time: '3 days ago',
      isRead: true,
    ),
  ];

  static const List<String> colors = [
    'Black',
    'White',
    'Blue',
    'Red',
    'Pink',
    'Gray',
    'Brown',
    'Green',
    'Yellow',
    'Purple',
  ];

  static const List<String> seasons = [
    'All Season',
    'Spring',
    'Summer',
    'Fall',
    'Winter',
  ];

  static const List<String> dressPiecesOptions = [
    '1 Piece',
    '2 Piece',
    '3 Piece',
  ];

  static const List<String> styles = [
    'Casual',
    'Formal',
    'Streetwear',
    'Minimalist',
    'Bohemian',
  ];

  static const Map<String, String> weatherSuggestions = {
    'Clear':
        '☀️ Perfect weather for casual outings. Light fabrics recommended.',
    'Cloudy': '☁️ A light jacket would be perfect for today.',
    'Rainy': '🌧️ Don\'t forget your raincoat and waterproof shoes.',
    'Cold': '❄️ Layer up! Perfect for sweaters and boots.',
    'Hot': '🔥 Stay cool with breathable fabrics and light colors.',
  };
}
