// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5gFrVbblxJZM_rKnkIf_bFEjezOxmYI',
    appId: '1:577840057220:web:287914f4f9ea063a462bd1',
    messagingSenderId: '577840057220',
    projectId: 'smart-wardrobe-aiman',
    authDomain: 'smart-wardrobe-aiman.firebaseapp.com',
    storageBucket: 'smart-wardrobe-aiman.firebasestorage.app',
    measurementId: 'G-3YDZ6EPV4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD35HvV6yADo9b5Gqq7D9BjzaKJ-J9FtF0',
    appId: '1:577840057220:android:599f878f66305ca6462bd1',
    messagingSenderId: '577840057220',
    projectId: 'smart-wardrobe-aiman',
    storageBucket: 'smart-wardrobe-aiman.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHB3pHtbStY8u287Q9EmwsjkLZcwMX9vM',
    appId: '1:577840057220:ios:bade8db1769eebbf462bd1',
    messagingSenderId: '577840057220',
    projectId: 'smart-wardrobe-aiman',
    storageBucket: 'smart-wardrobe-aiman.firebasestorage.app',
    iosBundleId: 'com.example.smartwardrobe',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHB3pHtbStY8u287Q9EmwsjkLZcwMX9vM',
    appId: '1:577840057220:ios:bade8db1769eebbf462bd1',
    messagingSenderId: '577840057220',
    projectId: 'smart-wardrobe-aiman',
    storageBucket: 'smart-wardrobe-aiman.firebasestorage.app',
    iosBundleId: 'com.example.smartwardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO5gFrVbblxJZM_rKnkIf_bFEjezOxmYI',
    appId: '1:577840057220:web:1592175712e71059462bd1',
    messagingSenderId: '577840057220',
    projectId: 'smart-wardrobe-aiman',
    authDomain: 'smart-wardrobe-aiman.firebaseapp.com',
    storageBucket: 'smart-wardrobe-aiman.firebasestorage.app',
    measurementId: 'G-K1ZN6SB22W',
  );
}
